version: "3.9"
services:
  app_service:
    image: screst/app_service # specify name of image on Docker Hub
    restart: "always" # automatically restart container when server crashes
    environment: # set up environment variables
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP} 
    ports:
      - "8000:8000" # expose port 8000 so that applications outside the container can connect to it 
    depends_on: # only run app_service after auth_service has started
      auth_service:
        condition: service_started
  auth_service:
    image: screst/auth_service
    restart: "always" # automatically restart container when server crashes
    ports:
      - "3000:3000" # expose port 3000 so that applications outside the container can connect to it 